version: "1"

services:    
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: "keycloak"
    ports:
      - 8080:8080/tcp
    command:
      - start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=changeme
    volumes:
      - ./import:/opt/keycloak/data/import
      - ./conf:/opt/keycloak/conf
    networks:
      - internal
    depends_on:
      postgres:
        condition: "service_healthy"

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: 'keycloak'
      POSTGRES_USER: 'keycloak'
      POSTGRES_PASSWORD: 'changeme'
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 30s
      retries: 10
    ports:
      - 5432:5432
    expose:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgres
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
