version: "1"

services:    

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    expose:
      - 5432:5432
    environment:
      POSTGRES_DB: 'keycloak'
      POSTGRES_USER: 'keycloak'
      POSTGRES_PASSWORD: 'changeme'
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 30s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgres
    networks:
      - internal

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    expose:
      - 27017:27017
    volumes:
      - "mongo_data:/data/mongo"
    networks:
      - internal

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    restart: unless-stopped
    ports:
      - 9200:9200/tcp
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    volumes:
      - "log_data:/usr/share/opensearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - internal

  graylog:
    image: graylog/graylog:5.1
    container_name: graylog
    restart: unless-stopped
    ports:
      - 9000:9000/tcp   # Graylog web interface and REST API
      - 1514:1514/tcp   # Syslog
      - 1514:1514/udp   # Syslog
      - 12201:12201/tcp # GELF
      - 12201:12201/udp # GELF
    expose:
      - 9000:9000/tcp   # Graylog web interface and REST API
      - 1514:1514/tcp   # Syslog
      - 1514:1514/udp   # Syslog
      - 12201:12201/tcp # GELF
      - 12201:12201/udp # GELF
    environment:
      # CHANGE ME (must be at least 16 characters)!
      GRAYLOG_PASSWORD_SECRET: "somepasswordpepper"
      GRAYLOG_ROOT_PASSWORD_SHA2: "057ba03d6c44104863dc7361fe4578965d1887360f90a0895882e58a6248fc86" #changeme
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      GRAYLOG_TIMEZONE: "Europe/Berlin"
      TZ: "Europe/Berlin"
      #GRAYLOG_TRANSPORT_EMAIL_PROTOCOL: "smtp"
      #GRAYLOG_TRANSPORT_EMAIL_WEB_INTERFACE_URL: "http://192.168.3.233:9000/"
      #GRAYLOG_TRANSPORT_EMAIL_HOSTNAME: "${SMTP_ADDRESS}"
      #GRAYLOG_TRANSPORT_EMAIL_ENABLED: "true"
      #GRAYLOG_TRANSPORT_EMAIL_PORT: "587"
      #GRAYLOG_TRANSPORT_EMAIL_USE_AUTH: "true"
      #GRAYLOG_TRANSPORT_EMAIL_AUTH_USERNAME: ${SMTP_USER}
      #GRAYLOG_TRANSPORT_EMAIL_AUTH_PASSWORD: ${SMTP_PWD}
      #GRAYLOG_TRANSPORT_EMAIL_USE_TLS: "true"
      #GRAYLOG_TRANSPORT_EMAIL_USE_SSL: "false"
      #GRAYLOG_TRANSPORT_FROM_EMAIL: ${SMTP_USER}
      #GRAYLOG_TRANSPORT_SUBJECT_PREFIX: "[graylog]"

    entrypoint: /usr/bin/tini -- wait-for-it opensearch:9200 -- /docker-entrypoint.sh
    volumes:
      - "./config/graylog/graylog.conf:/usr/share/graylog/config/graylog.conf"
      - "graylog_data:/usr/share/graylog/data"
    networks:
      - internal
    depends_on:
      opensearch:
        condition: "service_started"
      mongo:
        condition: "service_started"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: "keycloak"
    restart: unless-stopped
    command:
      - start-dev --import-realm
    ports:
      - 8080:8080/tcp
    expose:
      - 8080:8080/tcp
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=changeme
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=changeme
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_LOG=gelf
      - KC_LOG_GELF_LEVEL=info
      - KC_LOG_GELF_HOST=graylog
      - KC_LOG_GELF_PORT=12201
    volumes:
      - ./import:/opt/keycloak/data/import
    networks:
      - internal
    depends_on:
      postgres:
        condition: "service_healthy"
      graylog:
        condition: "service_started"

networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local
  log_data:
    driver: local
  graylog_data:
    driver: local
