version: "1"

services:    
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: "keycloak"
    restart: unless-stopped
    command:
      - start-dev --import-realm
    ports:
      - 8080:8080/tcp
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=changeme
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=changeme
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_LOG=gelf
      - KC_LOG_GELF_LEVEL=info
      - KC_LOG_GELF_HOST=localhost
      - KC_LOG_GELF_PORT=12201
    volumes:
      - ./import:/opt/keycloak/data/import
    networks:
      - internal
    depends_on:
      postgres:
        condition: "service_healthy"

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'keycloak'
      POSTGRES_USER: 'keycloak'
      POSTGRES_PASSWORD: 'changeme'
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 30s
      retries: 10
    expose:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgres
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
